name: 'Release'

on:
  push:
    branches:
      - release

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            name: 'macOS ARM64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            name: 'macOS Intel'
          - platform: 'windows-latest'
            args: ''
            name: 'Windows'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          npm install

      - name: Install dependencies (macOS only)
        if: matrix.platform == 'macos-latest'
        run: |
          npm install

      - name: Setup macOS signing
        if: matrix.platform == 'macos-latest'
        run: |
          echo "$APPLE_API_KEY_CONTENT" > "$RUNNER_TEMP/api.p8"
        env:
          APPLE_API_KEY_CONTENT: ${{ secrets.APPLE_API_KEY_CONTENT }}

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_API_KEY_PATH: ${{ runner.temp }}/api.p8
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          tagName: v__VERSION__
          releaseName: 'DeepRant v__VERSION__'
          releaseBody: |
            请查看附件下载对应系统的安装包：
            - Windows: .msi 安装包
            - macOS Intel: .dmg (x64) 安装包
            - macOS Apple Silicon: .dmg (arm64) 安装包
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          tauriScript: 'npm run tauri'
